-- 1. Create a table for public profiles linked to auth.users
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  email text,
  full_name text,
  is_pro boolean default false,
  pro_since timestamptz,
  subscription_id text, -- Placeholder for Stripe/Razorpay/LemonSqueezy ID
  created_at timestamptz default now()
);

-- 2. Enable Row Level Security (RLS) to protect data
alter table profiles enable row level security;

-- 3. Policy: Users can view ONLY their own profile
create policy "Users can view own profile" on profiles
  for select using (auth.uid() = id);

-- 4. Policy: Users can update their own profile (e.g. changing name)
-- Note: They cannot change 'is_pro' themselves; that requires a service_role key or admin
create policy "Users can update own profile" on profiles
  for update using (auth.uid() = id);

-- 5. Trigger: Automatically create a profile row when a new user Signs Up via Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 6. (Optional) Create a 'Questions' table for the future Question Bank
create table questions (
  id bigint generated by default as identity primary key,
  content text not null,
  subject text,
  topic text,
  difficulty text,
  class_level text,
  is_verified boolean default false,
  created_at timestamptz default now()
);

-- Enable Vector Search (requires enabling 'vector' extension in Supabase Database > Extensions first)
-- create extension if not exists vector;
-- alter table questions add column embedding vector(1536);
