import React, { useState, useRef } from 'react';
import { Brain, Check, X, RefreshCw, Download, Loader2, FileText, ImageIcon, Play, BookOpen, BookmarkPlus, CheckCheck, Lock, Target, AlertTriangle, Info } from 'lucide-react';
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { QuizQuestion, QuizType } from '../types';
import MarkdownRenderer from './MarkdownRenderer';
import InteractiveQuiz from './InteractiveQuiz';
import { addToDeck } from '../services/srsService';

interface QuizViewProps {
  questions: QuizQuestion[];
  onGenerateMore: () => void;
  isLoadingMore: boolean;
  fileContext: string | null;
  fileMimeType: string;
  isPro?: boolean;
}

const QuizView: React.FC<QuizViewProps> = ({ questions, onGenerateMore, isLoadingMore, fileContext, fileMimeType, isPro = false }) => {
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [showResults, setShowResults] = useState(false);
  const [isDownloading, setIsDownloading] = useState(false);
  
  // Competitive Mode State
  const [examMode, setExamMode] = useState(true); 

  const [savedItems, setSavedItems] = useState<Record<number, boolean>>({});
  const [viewMode, setViewMode] = useState<'REVIEW' | 'INTERACTIVE'>('REVIEW');

  const printRef = useRef<HTMLDivElement>(null);

  const handleOptionSelect = (questionId: number, optionIndex: number) => {
    if (showResults) return;
    
    setSelectedAnswers(prev => {
        if (prev[questionId] === optionIndex) {
            const newState = { ...prev };
            delete newState[questionId];
            return newState;
        }
        return {
            ...prev,
            [questionId]: optionIndex
        };
    });
  };

  const getResultsData = () => {
    let correct = 0;
    let incorrect = 0;
    let unattempted = 0;

    questions.forEach(q => {
      if (selectedAnswers[q.id] === undefined) {
        unattempted++;
      } else if (selectedAnswers[q.id] === q.correctIndex) {
        correct++;
      } else {
        incorrect++;
      }
    });

    // Scoring logic
    const score = examMode 
        ? (correct * 4) - (incorrect * 1) 
        : correct;
    
    const maxScore = examMode ? questions.length * 4 : questions.length;
    const accuracy = questions.length > 0 
        ? Math.round((correct / (questions.length - unattempted || 1)) * 100) 
        : 0;

    return { score, maxScore, correct, incorrect, unattempted, accuracy };
  };

  const resetQuiz = () => {
    setSelectedAnswers({});
    setShowResults(false);
    setSavedItems({});
  };

  const handleAddToReview = (q: QuizQuestion) => {
    const success = addToDeck(q.question, q.options[q.correctIndex], q.explanation, QuizType.MULTIPLE_CHOICE);
    if (success) {
        setSavedItems(prev => ({ ...prev, [q.id]: true }));
    }
  };

  const handleDownloadWord = () => {
     if (!isPro) {
         alert("Downloads are available for Pro users only.");
         return;
     }
     const content = `
        <html xmlns:o='urn:schemas-microsoft-com:office:office' xmlns:w='urn:schemas-microsoft-com:office:word' xmlns='http://www.w3.org/TR/REC-html40'>
        <head>
            <meta charset='utf-8'>
            <title>Quiz</title>
            <style>
                body { font-family: 'Arial', sans-serif; }
                h1 { font-size: 24px; font-weight: bold; margin-bottom: 20px; }
                h2 { font-size: 18px; font-weight: bold; margin-top: 30px; margin-bottom: 10px; }
                p { margin-bottom: 10px; }
                .question { margin-bottom: 20px; }
                .options { list-style-type: none; padding-left: 0; }
                .options li { margin-bottom: 5px; }
                .answer-key { margin-top: 50px; border-top: 1px solid #ccc; pt-4; }
                .figure { margin: 15px 0; padding: 10px; border: 1px dashed #ccc; background: #f9f9f9; text-align: center; font-style: italic; color: #666; }
            </style>
        </head>
        <body>
           <h1>Practice Quiz</h1>
           <p>Generated by Crazu Academy</p>
           <br/>
           ${questions.map((q, i) => `
              <div class="question">
                  <p><strong>${i+1}. ${q.question}</strong></p>
                  ${q.diagramSVG ? `<div class="figure">[Diagram requires Word drawing canvas or PDF download.]</div>` : ''}
                  <ul class="options">
                    ${q.options.map((opt, oi) => `<li>${String.fromCharCode(65+oi)}. ${opt}</li>`).join('')}
                  </ul>
              </div>
           `).join('')}
           <div class="answer-key">
               <h2>Answer Key</h2>
               ${questions.map((q, i) => `<p><strong>${i+1}:</strong> ${String.fromCharCode(65+q.correctIndex)}</p>`).join('')}
           </div>
        </body>
        </html>
     `;
     const blob = new Blob([content], { type: 'application/msword' });
     const url = URL.createObjectURL(blob);
     const a = document.createElement('a');
     a.href = url;
     a.download = 'crazu-exam-prep.doc';
     document.body.appendChild(a);
     a.click();
     document.body.removeChild(a);
     URL.revokeObjectURL(url);
  };

  const handleDownloadPdf = async () => {
    if (!isPro) {
        alert("Downloads are available for Pro users only.");
        return;
    }
    if (!printRef.current) return;
    setIsDownloading(true);

    try {
        const container = document.createElement('div');
        container.style.position = 'fixed';
        container.style.top = '0';
        container.style.left = '0';
        container.style.width = '800px'; 
        container.style.zIndex = '-1000'; 
        container.style.backgroundColor = '#ffffff';
        container.style.color = '#000000';
        
        const clone = printRef.current.cloneNode(true) as HTMLElement;
        clone.classList.remove('dark'); 
        clone.classList.remove('hidden'); 
        clone.style.display = 'block';
        clone.style.width = '100%';
        clone.style.padding = '40px';

        const allElements = clone.querySelectorAll('*');
        allElements.forEach((el) => {
            if (el instanceof HTMLElement) {
                 el.style.color = 'black';
                 el.style.borderColor = '#000000';
            }
        });

        container.appendChild(clone);
        document.body.appendChild(container);

        await new Promise(r => setTimeout(r, 800));

        const canvas = await html2canvas(container, {
            scale: 2,
            useCORS: true,
            backgroundColor: "#FFFFFF",
            windowWidth: 800
        });

        document.body.removeChild(container);

        const imgData = canvas.toDataURL('image/jpeg', 0.8);
        const pdf = new jsPDF({
            orientation: 'portrait',
            unit: 'mm',
            format: 'a4',
            compress: true
        });

        const imgWidth = 210;
        const pageHeight = 297;
        const imgHeight = (canvas.height * imgWidth) / canvas.width;
        
        let heightLeft = imgHeight;
        let position = 0;

        pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight, undefined, 'FAST');
        heightLeft -= pageHeight;

        while (heightLeft >= 0) {
            position = heightLeft - imgHeight;
            pdf.addPage();
            pdf.addImage(imgData, 'JPEG', 0, position, imgWidth, imgHeight, undefined, 'FAST');
            heightLeft -= pageHeight;
        }

        pdf.save('crazu-exam-prep.pdf');

    } catch (error) {
        console.error("PDF generation failed:", error);
    } finally {
        setIsDownloading(false);
    }
  };

  if (viewMode === 'INTERACTIVE' && fileContext) {
      return (
          <div className="animate-in fade-in duration-500">
             <InteractiveQuiz 
                fileContext={fileContext}
                fileMimeType={fileMimeType}
                onExit={() => setViewMode('REVIEW')}
             />
          </div>
      )
  }

  const results = getResultsData();

  return (
    <div className="animate-in fade-in duration-500">
      <div className="border-2 border-black dark:border-white p-8 bg-brand-white dark:bg-black">
        
        {/* Exam Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 border-b-2 border-black dark:border-white/20 pb-6 gap-4">
          <div className="flex items-center gap-4">
            <div className="p-3 bg-black text-white dark:bg-white dark:text-black">
              <Target className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-3xl font-bold text-black dark:text-white uppercase tracking-tighter">Exam Simulator</h2>
              <div className="flex items-center gap-2 mt-1">
                 <button 
                    onClick={() => setExamMode(!examMode)}
                    className={`text-[10px] font-bold uppercase px-2 py-0.5 border ${examMode ? 'bg-red-500 text-white border-red-500' : 'bg-zinc-100 text-zinc-500 border-zinc-200'}`}
                 >
                    {examMode ? 'Competitive Mode (+4 / -1)' : 'Board Mode (+1 / 0)'}
                 </button>
                 {examMode && <span className="text-[10px] font-bold text-red-500 uppercase flex items-center gap-1 animate-pulse"><AlertTriangle className="w-3 h-3"/> Negative Marking Active</span>}
              </div>
            </div>
          </div>
          
          <div className="flex flex-col md:flex-row items-end md:items-center gap-4">
             {showResults ? (
                <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mr-4">
                    <div className="text-right">
                        <span className="block text-2xl font-bold text-black dark:text-white">{results.score}<span className="text-sm text-zinc-400">/{results.maxScore}</span></span>
                        <span className="text-[10px] font-bold uppercase text-zinc-500">Final Score</span>
                    </div>
                    <div className="text-right">
                        <span className="block text-2xl font-bold text-brand-yellow">{results.accuracy}%</span>
                        <span className="text-[10px] font-bold uppercase text-zinc-500">Accuracy</span>
                    </div>
                    <div className="text-right hidden md:block">
                        <span className="block text-2xl font-bold text-green-500">{results.correct}</span>
                        <span className="text-[10px] font-bold uppercase text-zinc-500">Correct</span>
                    </div>
                    <div className="text-right hidden md:block">
                        <span className="block text-2xl font-bold text-red-500">{results.incorrect}</span>
                        <span className="text-[10px] font-bold uppercase text-zinc-500">Incorrect</span>
                    </div>
                </div>
             ) : (
                <button
                    onClick={() => setViewMode('INTERACTIVE')}
                    className="flex items-center gap-2 px-6 py-3 bg-black dark:bg-white text-white dark:text-black font-bold uppercase hover:bg-brand-yellow hover:text-black dark:hover:bg-brand-yellow dark:hover:text-black transition-colors border-2 border-transparent"
                >
                    <Play className="w-5 h-5" /> Interactive Drill
                </button>
             )}

             <div className="flex gap-2">
                 <button
                    onClick={handleDownloadWord}
                    className={`hidden md:flex items-center gap-2 px-4 py-3 font-bold uppercase border-2 transition-colors ${!isPro ? 'opacity-50 cursor-not-allowed bg-zinc-200 text-zinc-500' : 'bg-zinc-100 dark:bg-zinc-900 text-black dark:text-white hover:bg-zinc-200 dark:hover:bg-zinc-800 border-transparent'}`}
                    title={isPro ? "Download Word" : "Pro Only"}
                 >
                    {isPro ? <FileText className="w-5 h-5" /> : <Lock className="w-5 h-5" />}
                 </button>
                 <button
                    onClick={handleDownloadPdf}
                    disabled={isDownloading || !isPro}
                    className={`hidden md:flex items-center gap-2 px-4 py-3 font-bold uppercase border-2 transition-colors ${!isPro ? 'opacity-50 cursor-not-allowed bg-zinc-200 text-zinc-500' : 'bg-brand-yellow text-black hover:bg-black hover:text-white border-transparent'}`}
                    title={isPro ? "Download PDF" : "Pro Only"}
                 >
                    {isDownloading ? <Loader2 className="w-5 h-5 animate-spin"/> : (isPro ? <Download className="w-5 h-5" /> : <Lock className="w-5 h-5" />)}
                 </button>
             </div>
          </div>
        </div>

        {/* Results Overview (Post-submit) */}
        {showResults && (
            <div className="mb-12 grid grid-cols-1 md:grid-cols-3 gap-6 animate-in slide-in-from-top-4">
                <div className="p-6 border-2 border-black dark:border-white bg-green-50 dark:bg-green-900/10">
                    <div className="flex items-center justify-between mb-2">
                        <span className="font-bold uppercase text-xs text-green-600">Perfect Recall</span>
                        <Check className="w-4 h-4 text-green-600" />
                    </div>
                    <div className="text-3xl font-bold text-green-700 dark:text-green-400">+{results.correct * (examMode ? 4 : 1)} Marks</div>
                    <p className="text-[10px] font-bold text-green-600/60 uppercase">Earned from {results.correct} correct answers</p>
                </div>
                <div className="p-6 border-2 border-black dark:border-white bg-red-50 dark:bg-red-900/10">
                    <div className="flex items-center justify-between mb-2">
                        <span className="font-bold uppercase text-xs text-red-600">Negative Impact</span>
                        <X className="w-4 h-4 text-red-600" />
                    </div>
                    <div className="text-3xl font-bold text-red-700 dark:text-red-400">-{examMode ? results.incorrect : 0} Marks</div>
                    <p className="text-[10px] font-bold text-red-600/60 uppercase">Lost from {results.incorrect} wrong answers</p>
                </div>
                <div className="p-6 border-2 border-black dark:border-white bg-zinc-50 dark:bg-zinc-900">
                    <div className="flex items-center justify-between mb-2">
                        <span className="font-bold uppercase text-xs text-zinc-500">Unattempted</span>
                        <Info className="w-4 h-4 text-zinc-500" />
                    </div>
                    <div className="text-3xl font-bold text-zinc-700 dark:text-zinc-400">0 Marks</div>
                    <p className="text-[10px] font-bold text-zinc-500/60 uppercase">{results.unattempted} questions skipped</p>
                </div>
            </div>
        )}

        {/* Question List */}
        <div className="space-y-16">
            <QuestionList 
              questions={questions} 
              selectedAnswers={selectedAnswers} 
              showResults={showResults} 
              onSelect={handleOptionSelect} 
              onAddToReview={handleAddToReview}
              savedItems={savedItems}
            />
        </div>

        <div className="mt-12 pt-8 border-t-2 border-black dark:border-white/20 flex flex-col items-start gap-6">
           <button
            onClick={onGenerateMore}
            disabled={isLoadingMore}
            className={`
              flex items-center gap-2 px-6 py-3 font-bold uppercase tracking-wider text-sm transition-all
              ${isLoadingMore
                ? 'text-zinc-400 cursor-wait'
                : 'text-zinc-600 dark:text-zinc-400 hover:text-black dark:hover:text-white border-b-2 border-transparent hover:border-black dark:hover:border-white'
              }
            `}
          >
            {isLoadingMore ? 'Loading...' : '+ Generate High-Yield Questions'}
          </button>

          <div className="flex gap-4">
            {!showResults ? (
              <button
                onClick={() => setShowResults(true)}
                disabled={Object.keys(selectedAnswers).length === 0}
                className={`
                  px-10 py-4 font-bold uppercase tracking-widest text-lg transition-transform active:scale-95 shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]
                  ${Object.keys(selectedAnswers).length === 0
                    ? 'bg-zinc-200 dark:bg-zinc-800 text-zinc-400 dark:text-zinc-600 cursor-not-allowed'
                    : 'bg-brand-yellow text-black hover:bg-black hover:text-white'
                  }
                `}
              >
                End Test & Calculate Rank
              </button>
            ) : (
              <button
                onClick={resetQuiz}
                className="flex items-center gap-3 px-8 py-4 bg-brand-yellow text-black font-bold uppercase tracking-wider hover:bg-black hover:text-white transition-colors border-2 border-black"
              >
                <RefreshCw className="w-5 h-5" />
                Retake Mock Test
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Hidden Print View */}
      <div ref={printRef} className="hidden text-black bg-white">
            <div className="p-8">
                <h1 className="text-4xl font-bold mb-2 uppercase text-black">Competitive Mock Test</h1>
                <p className="text-zinc-500 mb-8 border-b-2 border-black pb-4">Generated by Crazu Academy</p>
                
                <div className="space-y-8">
                    {questions.map((q, idx) => (
                        <div key={idx} className="mb-8 break-inside-avoid">
                            <div className="flex gap-3 mb-3">
                                <span className="font-bold text-lg">{idx + 1}.</span>
                                <div className="text-lg font-medium w-full">
                                    <MarkdownRenderer content={q.question} inline />
                                </div>
                            </div>
                            <div className="pl-8 grid grid-cols-1 gap-2">
                                {q.options.map((opt, optIdx) => (
                                    <div key={optIdx} className="flex gap-2 items-start">
                                        <div className="w-6 font-bold">{String.fromCharCode(65 + optIdx)}.</div>
                                        <div><MarkdownRenderer content={opt} inline /></div>
                                    </div>
                                ))}
                            </div>
                        </div>
                    ))}
                </div>

                <div className="mt-12 pt-8 border-t-2 border-black break-before-page">
                    <h2 className="text-2xl font-bold mb-6 uppercase">Official Answer Key</h2>
                    <div className="grid grid-cols-4 gap-4">
                        {questions.map((q, idx) => (
                            <div key={idx} className="flex items-center gap-2 text-sm border p-2 border-black">
                                <span className="font-bold">Q{idx + 1}:</span> 
                                <span>{String.fromCharCode(65 + q.correctIndex)}</span>
                            </div>
                        ))}
                    </div>
                </div>
            </div>
      </div>
    </div>
  );
};

const QuestionList = ({ questions, selectedAnswers, showResults, onSelect, onAddToReview, savedItems }: any) => (
  <>
    {questions.map((q: QuizQuestion, qIdx: number) => (
      <div key={q.id || qIdx} className="pb-8 last:pb-0 border-b border-zinc-100 dark:border-zinc-900 last:border-0">
        <div className="flex justify-between items-start gap-4">
            <div className="text-xl font-bold text-black dark:text-white mb-6 flex flex-col gap-4 flex-1">
            <div className="flex gap-4">
                <span className="text-brand-yellow font-mono text-2xl flex-shrink-0">{q.id}.</span>
                <div className="w-full"><MarkdownRenderer content={q.question} /></div>
            </div>
            {q.diagramSVG && (
                <div className="ml-10 p-4 bg-white dark:bg-zinc-900 border-2 border-zinc-200 dark:border-zinc-800 rounded-none max-w-lg">
                    <div className="flex items-center gap-2 mb-2 text-xs font-bold uppercase text-zinc-500">
                        <ImageIcon className="w-4 h-4" /> Figure
                    </div>
                    <div dangerouslySetInnerHTML={{ __html: q.diagramSVG }} className="w-full overflow-x-auto dark:invert-[.85]" />
                </div>
            )}
            </div>
            
            {showResults && (
                <button
                    onClick={() => onAddToReview(q)}
                    disabled={savedItems[q.id]}
                    className={`
                        p-2 border-2 transition-all flex items-center gap-2 text-xs font-bold uppercase
                        ${savedItems[q.id] 
                            ? 'border-brand-yellow bg-brand-yellow/10 text-black dark:text-white' 
                            : 'border-zinc-200 text-zinc-400 hover:border-black dark:hover:border-white hover:text-black dark:hover:text-white'
                        }
                    `}
                >
                    {savedItems[q.id] ? <CheckCheck className="w-4 h-4"/> : <BookmarkPlus className="w-4 h-4"/>}
                    <span className="hidden sm:inline">{savedItems[q.id] ? 'Saved' : 'Add to Review'}</span>
                </button>
            )}
        </div>
        
        <div className="grid grid-cols-1 gap-4 pl-0 md:pl-12">
          {q.options.map((option: string, optIdx: number) => {
            let btnClass = "border-2 border-zinc-200 dark:border-zinc-700 bg-transparent text-zinc-600 dark:text-zinc-300 hover:border-black dark:hover:border-white";
            let icon = null;
            
            if (showResults) {
              if (optIdx === q.correctIndex) {
                btnClass = "border-2 border-black dark:border-white bg-brand-yellow text-black font-bold";
                icon = <Check className="w-5 h-5 text-black" />;
              } else if (selectedAnswers[q.id] === optIdx) {
                btnClass = "border-2 border-black dark:border-white bg-black dark:bg-red-900/30 text-white dark:text-white line-through";
                  icon = <X className="w-5 h-5" />;
              } else {
                btnClass = "border-2 border-zinc-100 dark:border-zinc-800 opacity-30";
              }
            } else if (selectedAnswers[q.id] === optIdx) {
              btnClass = "border-2 border-black dark:border-white bg-black dark:bg-white text-white dark:text-black font-bold";
            }

            return (
              <button
                key={optIdx}
                onClick={() => onSelect(q.id, optIdx)}
                disabled={showResults}
                className={`
                  w-full text-left p-5 transition-all flex items-center justify-between group
                  ${btnClass}
                `}
              >
                <span className="text-lg w-full">
                  <MarkdownRenderer content={option} inline={true} className="!text-inherit" />
                </span>
                {icon}
              </button>
            );
          })}
        </div>

        {showResults && (
          <div className="mt-6 ml-0 md:ml-12 p-6 border-l-4 border-brand-yellow bg-zinc-50 dark:bg-zinc-900 text-black dark:text-white">
            <span className="font-bold uppercase tracking-wider text-[10px] block mb-2 text-zinc-500">Solution Methodology</span>
            <MarkdownRenderer content={q.explanation} />
          </div>
        )}
      </div>
    ))}
  </>
);

export default QuizView;